// <auto-generated />
namespace IsThereAnyNews.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rss_clicked_event : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rss_clicked_event));
        
        string IMigrationMetadata.Id
        {
            get { return "201605291350387_rss_clicked_event"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
