// <auto-generated />
namespace IsThereAnyNews.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m0002_Trigger_User_InsteadOfDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m0002_Trigger_User_InsteadOfDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201607052316076_m0002_Trigger_User_InsteadOfDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
