// <auto-generated />
namespace IsThereAnyNews.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rsschannelupdatedevent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rsschannelupdatedevent));
        
        string IMigrationMetadata.Id
        {
            get { return "201604171153307_rsschannel updated event"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
